### ISSUE TITLE
Compatibility broken with Plone < 5.2

### ISSUE THREAD

**Issue by laulaz** [collective/collective.mailchimp#67]
@fredvd this line in your commit c637b81606bdd469e81e90aa21114adef1b651fd is problematic :
https://github.com/collective/collective.mailchimp/blob/98a648510ca806ead6d4a629a6e2b199bafcd561/src/collective/mailchimp/browser/newsletter.py#L13

`safe_text` is not there in Plone 4 / 5.0 / 5.1 (still supported in `setup.py`)

**Comment by fremwilplone** [comment]
Those Plone releases are however all out of any support since december 2022.  For those, integrators can stick to the old release. It would also mean we need to keep Python 2.7 compatibilty. 

I suggest the next relase is for 4.x (semantic version and targets Plone 5.2/Python 3 and Plone 6 only.   Then we can fix this issue on a new 3.X release where we keep compatibility and do security related fixes only.

@mauritsvanrees you have some feature/improvement PR's .  These are I assume Plone 5.2/6 only as well, or ?

**Comment by fredvd** [comment]
Those Plone releases are however all out of any support since december 2022. For those, integrators can stick to the old release. It would also mean we need to keep Python 2.7 compatibilty.

I suggest the next relase is for 4.x (semantic version and targets Plone 5.2/Python 3 and Plone 6 only. Then we can fix this issue on a new 3.X release where we keep compatibility and do security related fixes only.

@mauritsvanrees you have some feature/improvement PR's . These are I assume Plone 5.2/6 only as well, or ?

**Comment by mauritsvanrees** [comment]
Yes, in https://github.com/collective/collective.mailchimp/pull/63 I proposed to drop Python 2 support, so also drop Plone 5.1 and earlier.

**Comment by fredvd** [comment]
@laulaz Do you agree with that?  Do you have to support large installatin < Plone 5.2 that run into trouble with this?  Can they keep running with a low volume 3.x maintenance branch where we do bigger improvements for Supported Plone releases only on 4.x? 

You can still backport improvements from 4.x to 3.x when it is required.

**Comment by mauritsvanrees** [comment]
I have created maintenance branch 3.x for older Plone/Python versions and released 3.1.1.
See also [this comment](https://github.com/collective/collective.mailchimp/pull/63#issuecomment-1508206906).

I have merged my PRs to master and released 4.0.0a1.
